# Generated by Django 4.0.6 on 2022-07-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_back', '0002_category_alter_post_options_alter_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_back.category'),
            preserve_default=False,
        ),
    ]
